# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 1.3.2
_src_path: gh:algorandfoundation/algokit-python-template
author_email: berniedev.work@gmail.com
author_name: FlamoDynamo
contract_name: contracts
deployment_language: python
preset_name: starter
project_name: NFT_Check_Status_Before_Pay

